# Generated by Django 3.0.1 on 2019-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
